

    
name: Build, Push, and Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    name: Build and Push Services
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - { name: contact-support-team, path: contact-support-team }
          - { name: profile-management, path: profile-management }
          - { name: order-management, path: order-management }
          - { name: shipping-and-handling, path: shipping-and-handling }
          - { name: product-inventory, path: product-inventory }
          - { name: ecommerce-ui, path: ecommerce-ui }
          - { name: product-catalog, path: product-catalog }

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build & Push Docker Image
        working-directory: ${{ matrix.service.path }}
        run: |
          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service.name }}"
          TAG="${{ github.run_number }}"

          docker build -t $IMAGE:$TAG .
          docker push $IMAGE:$TAG

  deploy:
    name: Deploy to EC2 Servers
    runs-on: ubuntu-latest
    needs: build-and-push  # Wait until all services are built

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Copy docker-compose.yml to Server 1
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST1 }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          source: "docker-compose.yaml"
          target: "~/"

      - name: Deploy on Server 1
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST1 }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          script: |
            docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
            docker-compose -f ~/docker-compose.yaml pull
            docker-compose -f ~/docker-compose.yaml down
            docker-compose -f ~/docker-compose.yaml up -d

      - name: Copy docker-compose.yml to Server 2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST2 }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          source: "docker-compose.yaml"
          target: "~/"

      - name: Deploy on Server 2
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST2 }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          script: |
            docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
            docker-compose -f ~/docker-compose.yaml pull
            docker-compose -f ~/docker-compose.yaml down
            docker-compose -f ~/docker-compose.yaml up -d
